version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: offboarding_postgres
    environment:
      POSTGRES_DB: offboarding_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5441:5432"

  backend:
    build: ./Backend
    container_name: offboarding_backend
    ports:
      - "3011:3011"
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: root
      PGDATABASE: offboarding_db
      PGPORT: 5432

  employee-offboardinh:
    build: ./Employee-offboardinh
    container_name: employee_offboarding_ui
    ports:
      - "8020:80"
    depends_on:
      - backend

  hr-offboarding:
    build: ./HR-offboarding
    container_name: hr_offboarding_ui
    ports:
      - "8021:80"
    depends_on:
      - backend

volumes:
  postgres_data:

