version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-offboarding
    ports:
      - "5207:5432"
    environment:
      POSTGRES_DB: offboarding_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - offboarding-network

  backend:
    build: ./Backend
    container_name: backend-offboarding
    ports:
      - "3207:3207"
    depends_on:
      - postgres
    networks:
      - offboarding-network

  employee-offboarding:
    build: ./employee-offboarding
    container_name: employee-offboarding-ui
    ports:
      - "8013:80"
    depends_on:
      - backend
    networks:
      - offboarding-network

  hr-offboarding:
    build: ./hr-offboarding
    container_name: hr-offboarding-ui
    ports:
      - "8014:80"
    depends_on:
      - backend
    networks:
      - offboarding-network

volumes:
  pgdata:

networks:
  offboarding-network:

